"""
VisionMetrix 3D - Frequency Domain Processing
Module: fourier.py

Covers 2D Discrete Fourier Transform (DFT), 2D Fast Fourier Transform (FFT),
magnitude/phase spectrum analysis, Ideal filters, and Butterworth filtering
for periodic surface noise attenuation (e.g. factory conveyor vibrations).
"""

import cv2
import numpy as np
from typing import Tuple, List


def compute_fft2d(image: np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Computes centered 2D Fast Fourier Transform:
      F(u, v) = sum_x sum_y f(x, y) * exp(-j * 2*pi * (ux/M + vy/N))
      
    Returns:
      f_shift: Centered complex spectrum
      magnitude_spectrum: Log-scaled magnitude 20 * log(1 + |F(u, v)|) for display
      phase_spectrum: Phase angle in radians [-pi, pi]
    """
    if len(image.shape) == 3:
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    else:
        gray = image.copy()

    f = np.fft.fft2(gray.astype(np.float64))
    f_shift = np.fft.fftshift(f)

    magnitude = np.abs(f_shift)
    magnitude_spectrum = 20.0 * np.log1p(magnitude)
    magnitude_spectrum = cv2.normalize(magnitude_spectrum, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)

    phase_spectrum = np.angle(f_shift)
    return f_shift, magnitude_spectrum, phase_spectrum


def apply_ideal_filter(image: np.ndarray, cutoff_freq: float,
                       filter_type: str = "lowpass") -> Tuple[np.ndarray, np.ndarray]:
    """
    Applies an Ideal 2D frequency domain filter:
      Low-pass: H(u, v) = 1 if D(u, v) <= D_0 else 0
      High-pass: H(u, v) = 0 if D(u, v) <= D_0 else 1
    Note: Exhibits ringing artifacts (Gibbs phenomenon) due to sinc in spatial domain.
    """
    if len(image.shape) == 3:
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    else:
        gray = image.copy()

    h, w = gray.shape
    cy, cx = h // 2, w // 2

    y, x = np.ogrid[:h, :w]
    dist = np.sqrt((x - cx)**2 + (y - cy)**2)

    if filter_type == "lowpass":
        mask = (dist <= cutoff_freq).astype(np.float64)
    elif filter_type == "highpass":
        mask = (dist > cutoff_freq).astype(np.float64)
    else:
        raise ValueError("filter_type must be 'lowpass' or 'highpass'.")

    f = np.fft.fft2(gray.astype(np.float64))
    f_shift = np.fft.fftshift(f)
    f_filtered = f_shift * mask

    f_ishift = np.fft.ifftshift(f_filtered)
    img_back = np.fft.ifft2(f_ishift)
    img_filtered = np.real(img_back)
    img_filtered = np.clip(img_filtered, 0, 255).astype(np.uint8)

    mask_disp = (mask * 255).astype(np.uint8)
    return img_filtered, mask_disp


def apply_butterworth_filter(image: np.ndarray, cutoff_freq: float, order: int = 2,
                             filter_type: str = "lowpass") -> Tuple[np.ndarray, np.ndarray]:
    """
    Applies a Butterworth frequency domain filter:
      Lowpass: H(u, v) = 1 / (1 + (D(u, v) / D_0)^(2*n))
      Highpass: H(u, v) = 1 / (1 + (D_0 / D(u, v))^(2*n))
    Provides a smooth roll-off without sharp cutoff ringing artifacts.
    """
    if len(image.shape) == 3:
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    else:
        gray = image.copy()

    h, w = gray.shape
    cy, cx = h // 2, w // 2

    y, x = np.ogrid[:h, :w]
    dist = np.sqrt((x - cx)**2 + (y - cy)**2)
    dist = np.maximum(dist, 1e-5)  # Avoid division by zero at center

    if filter_type == "lowpass":
        mask = 1.0 / (1.0 + (dist / cutoff_freq)**(2 * order))
    elif filter_type == "highpass":
        mask = 1.0 / (1.0 + (cutoff_freq / dist)**(2 * order))
    else:
        raise ValueError("filter_type must be 'lowpass' or 'highpass'.")

    f = np.fft.fft2(gray.astype(np.float64))
    f_shift = np.fft.fftshift(f)
    f_filtered = f_shift * mask

    f_ishift = np.fft.ifftshift(f_filtered)
    img_back = np.fft.ifft2(f_ishift)
    img_filtered = np.real(img_back)
    img_filtered = np.clip(img_filtered, 0, 255).astype(np.uint8)

    mask_disp = cv2.normalize(mask, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)
    return img_filtered, mask_disp


def remove_periodic_noise(image: np.ndarray, notch_coords: List[Tuple[int, int]],
                          notch_radius: int = 8) -> Tuple[np.ndarray, np.ndarray]:
    """
    Applies a Notch Reject Filter to remove sinusoidal/periodic interference patterns
    generated by industrial electrical lines or machine motor hum.
    
    notch_coords: List of (u, v) frequency coordinates relative to center (cx, cy).
    """
    if len(image.shape) == 3:
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    else:
        gray = image.copy()

    h, w = gray.shape
    cy, cx = h // 2, w // 2

    mask = np.ones((h, w), dtype=np.float64)
    y, x = np.ogrid[:h, :w]

    for (nu, nv) in notch_coords:
        # Notch at (cx + nu, cy + nv) and its symmetric conjugate at (cx - nu, cy - nv)
        p1 = (cx + nu, cy + nv)
        p2 = (cx - nu, cy - nv)

        d1 = np.sqrt((x - p1[0])**2 + (y - p1[1])**2)
        d2 = np.sqrt((x - p2[0])**2 + (y - p2[1])**2)

        mask[d1 <= notch_radius] = 0.0
        mask[d2 <= notch_radius] = 0.0

    f = np.fft.fft2(gray.astype(np.float64))
    f_shift = np.fft.fftshift(f)
    f_filtered = f_shift * mask

    f_ishift = np.fft.ifftshift(f_filtered)
    img_back = np.fft.ifft2(f_ishift)
    restored = np.clip(np.real(img_back), 0, 255).astype(np.uint8)

    mask_disp = (mask * 255).astype(np.uint8)
    return restored, mask_disp
